pipeline {
  environment {
    PROJECT_ID = 'architect-certification-289902'
  }
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: gradle
spec:
  containers:
  - name: gradle
    image: gradle:6.3.0-jdk11
    command:
    - cat
    tty: true
"""      
    }
  }
  stages {
    stage('build and push docker image') {
      steps {
        container('gradle') {
          dir('eshop-adservice') {
            withCredentials([file(credentialsId: 'gcr-credential', variable: 'GCR_CREDENTIAL_JSON')]) {
              sh 'gradle jib --no-daemon --image "gcr.io/${PROJECT_ID}/adservice:${env.BUILD_ID}" -Djib.to.auth.username="_json_key" -Djib.to.auth.password="$( cat ${GCR_CREDENTIAL_JSON} )"'
            }
          }
        }
      }
    }
  }
}