INSERT INTO currency (currency_code, currency_value) VALUES (  'EUR', 1.0);
INSERT INTO currency (currency_code, currency_value) VALUES (  'USD', 1.1305);
INSERT INTO currency (currency_code, currency_value) VALUES (  'JPY', 126.40);
INSERT INTO currency (currency_code, currency_value) VALUES (  'BGN', 1.9558);
INSERT INTO currency (currency_code, currency_value) VALUES (  'CZK', 25.592);
INSERT INTO currency (currency_code, currency_value) VALUES (  'DKK', 7.4609);
INSERT INTO currency (currency_code, currency_value) VALUES (  'GBP', 0.85970);
INSERT INTO currency (currency_code, currency_value) VALUES (  'HUF', 315.51);
INSERT INTO currency (currency_code, currency_value) VALUES (  'PLN', 4.2996);
INSERT INTO currency (currency_code, currency_value) VALUES (  'RON', 4.7463);
INSERT INTO currency (currency_code, currency_value) VALUES (  'SEK', 10.5375);
INSERT INTO currency (currency_code, currency_value) VALUES (  'CHF', 1.1360);
INSERT INTO currency (currency_code, currency_value) VALUES (  'ISK', 136.80);
INSERT INTO currency (currency_code, currency_value) VALUES (  'NOK', 9.8040);
INSERT INTO currency (currency_code, currency_value) VALUES (  'HRK', 7.4210);
INSERT INTO currency (currency_code, currency_value) VALUES (  'RUB', 74.4208);
INSERT INTO currency (currency_code, currency_value) VALUES (  'TRY', 6.1247);
INSERT INTO currency (currency_code, currency_value) VALUES (  'AUD', 1.6072);
INSERT INTO currency (currency_code, currency_value) VALUES (  'BRL', 4.2682);
INSERT INTO currency (currency_code, currency_value) VALUES (  'CAD', 1.5128);
INSERT INTO currency (currency_code, currency_value) VALUES (  'CNY', 7.5857);
INSERT INTO currency (currency_code, currency_value) VALUES (  'HKD', 8.8743);
INSERT INTO currency (currency_code, currency_value) VALUES (  'IDR', 15999.40);
INSERT INTO currency (currency_code, currency_value) VALUES (  'ILS', 4.0875);
INSERT INTO currency (currency_code, currency_value) VALUES (  'INR', 79.4320);
INSERT INTO currency (currency_code, currency_value) VALUES (  'KRW', 1275.05);
INSERT INTO currency (currency_code, currency_value) VALUES (  'MXN', 21.7999);
INSERT INTO currency (currency_code, currency_value) VALUES (  'MYR', 4.6289);
INSERT INTO currency (currency_code, currency_value) VALUES (  'NZD', 1.6679);
INSERT INTO currency (currency_code, currency_value) VALUES (  'PHP', 59.083);
INSERT INTO currency (currency_code, currency_value) VALUES (  'SGD', 1.5349);
INSERT INTO currency (currency_code, currency_value) VALUES (  'THB', 36.012);
INSERT INTO currency (currency_code, currency_value) VALUES (  'ZAR', 16.0583);

INSERT INTO ad (category, redirect_url, text) VALUES ('photography','/products/2ZYFJ3GM2N','Film camera for sale. 50% off.');
INSERT INTO ad (category, redirect_url, text) VALUES ('vintage','/products/2ZYFJ3GM2N','Film camera for sale. 50% off.');
INSERT INTO ad (category, redirect_url, text) VALUES ('photography','/products/66VCHSJNUP','Vintage camera lens for sale. 20% off.');
INSERT INTO ad (category, redirect_url, text) VALUES ('vintage','/products/66VCHSJNUP','Vintage camera lens for sale. 20% off.');
INSERT INTO ad (category, redirect_url, text) VALUES ('vintage','/products/0PUK6V6EV0','Vintage record player for sale. 30% off.');
INSERT INTO ad (category, redirect_url, text) VALUES ('cycling','/products/9SIQT8TOJO', 'City Bike for sale. 10% off.');
INSERT INTO ad (category, redirect_url, text) VALUES ('cookware','/products/1YMWWN1N4O', 'Home Barista kitchen kit for sale. Buy one, get second kit for free');
INSERT INTO ad (category, redirect_url, text) VALUES ('gardening','/products/6E92ZMYYFZ', 'Air plants for sale. Buy two, get third one for free');
INSERT INTO ad (category, redirect_url, text) VALUES ('gardening','/products/L9ECAV7KIM', 'Terrarium for sale. Buy one, get second one for free');