pipeline {
  environment {
    PROJECT_ID = 'architect-certification-289902'
  }
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: docker
spec:
  containers:
  - name: docker
    image: docker
    command:
    - cat
    tty: true
  - name: dind
    image: docker:18.05-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
"""      
    }
  }
  stages {
    stage('build docker image') {
      steps {
        container('dind') {
          dir('eshop-currencyservice') {
            sh 'docker image build -t gcr.io/$PROJECT_ID/eshop-currencyservice:$BUILD_ID .'
          }
        }
      }
    }

    stage('push docker image') {
      steps {
        container('dind') {
          dir('eshop-currencyservice') {
            // withDockerRegistry([url:"https://gcr.io", credentialsId: "gcr-credential"]) {
            withCredentials([file(credentialsId: 'gcr-credential', variable: 'GCR_CREDENTIAL_JSON')]) {
              sh 'docker login -u _json_key -p "$( cat $GCR_CREDENTIAL_JSON )"'
              sh 'docker image push gcr.io/$PROJECT_ID/eshop-currencyservice:$BUILD_ID'
            }
          }
        }
      }
    }
  }
}